on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v2
      - run: echo "::add-matcher::.github/matcher.json"
      - run: |
          echo """
          File : $PWD/.github/workflows/main.yml:4:7
          Warn : message
          File : $PWD/.github/workflows/main.yml:14:42
          Error: error occurred
          ====
          """
      - id: foo
        uses: nemolize/vti@v1
        with:
          who-to-greet: 'Mona the Octocat'
      - run: echo random-number ${{ steps.foo.outputs.random-number }}
        shell: bash